services:
  backend:
    build:
      context: ./backend
  
    container_name: sweetspot-backend
    restart: always
    env_file: ./.env
    ports:
      - "5005:5005"
      
    # DB 서비스들이 healthy 상태가 된 후에 백엔드를 시작합니다.
   
    
    networks:
      - sweetspot-network

networks:
  sweetspot-network:
    driver: bridge
