services:
  # =================================================================
  #  DATABASE SERVICES
  # =================================================================
  # 1. DB Tunnel Service
  # 1. DB Tunnel Service
  db-tunnel:
    image: kroniak/ssh-client
    container_name: db-tunnel
    restart: always
    # [수정됨] 키를 복사하고 권한을 400으로 변경한 뒤 SSH 접속 시도
    entrypoint: /bin/sh
    command: -c "cp /root/ssh_key /root/id_rsa && chmod 400 /root/id_rsa && ssh -q -N -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o ExitOnForwardFailure=yes -L 0.0.0.0:3306:10.0.20.212:3306 -L 0.0.0.0:5432:10.0.20.212:5432 -i /root/id_rsa ubuntu@141.147.154.108"
    volumes:
      - "${SSH_KEY_PATH}:/root/ssh_key:ro"
    networks:
      - sweetspot-network

  # =================================================================
  #  BACKEND SERVICES
  # =================================================================
  # 3. 사용자용 API 서버 (Backend)
  api-server:
    build:
      context: .
      dockerfile: sweetspot-api/Dockerfile
    container_name: sweetspot-api
    restart: always
    ports:
      - "5005:5005"
    environment:
      SPRING_PROFILES_ACTIVE: local # 로컬 개발용
    env_file: ./.env
    networks:
      - sweetspot-network
    depends_on:
      - db-tunnel

  # 4. 관리자용 Admin 서버 (Backend)
  admin-server:
    build:
      context: .
      dockerfile: sweetspot-admin/Dockerfile
    container_name: sweetspot-admin
    restart: always
    ports:
      - "5007:5007"
    environment:
      SPRING_PROFILES_ACTIVE: local # 로컬 개발용
    env_file: ./.env
    volumes:
      - ./output:/app/output
      - ./csv-data:/app/csv-data
      - ./logs:/app/logs
    networks:
      - sweetspot-network
    depends_on:
      - db-tunnel

  # =================================================================
  #  FRONTEND SERVICES
  # =================================================================
  # 5. 관리자용 Frontend (React)
  admin-client:
    build:
      context: ./frontend-admin
      dockerfile: Dockerfile
    container_name: sweetspot-admin-client
    restart: always
    ports:
      - "5008:5008"
    environment:
      - VITE_API_BASE_URL=https://admin.sweetspot.kro.kr/api/admin
    networks:
      - sweetspot-network

networks:
  sweetspot-network:
    driver: bridge