server:
  forward-headers-strategy: native
  tomcat:
    max-http-form-post-size: 20MB

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

gemini:
  api:
    key: "${GEMINI_API_KEY}"
datasources:
  auth:
    driver-class-name: org.mariadb.jdbc.Driver
    # 실제 서버에서는 DB VM 에 직접 붙을 거면 .env 값 그대로 쓰는 게 깔끔
    url: ${SPRING_DATASOURCE_AUTH_URL}          # jdbc:mariadb://10.0.20.212:3306/sweetspot_auth
    username: ${SPRING_DATASOURCE_AUTH_USERNAME}
    password: ${SPRING_DATASOURCE_AUTH_PASSWORD}
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect
          hbm2ddl:
            auto: update

  domain:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_DOMAIN_URL}        # jdbc:postgresql://10.0.20.212:5432/sweetspot_places
    username: ${SPRING_DATASOURCE_DOMAIN_USERNAME}
    password: ${SPRING_DATASOURCE_DOMAIN_PASSWORD}
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          hbm2ddl:
            auto: update
          # Domain DB용 쿼리 로그 활성화
          show_sql: true
          format_sql: true
          highlight_sql: true