# sweetspot-api/src/main/resources/application-local.yml

spring:
  datasources:
    auth:
      driver-class-name: org.mariadb.jdbc.Driver
      url: ${SPRING_DATASOURCE_AUTH_URL}
      username: ${SPRING_DATASOURCE_AUTH_USERNAME}
      password: ${SPRING_DATASOURCE_AUTH_PASSWORD}
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MariaDBDialect
            hbm2ddl:
              auto: update
    domain:
      driver-class-name: org.postgresql.Driver
      url: ${SPRING_DATASOURCE_DOMAIN_URL}
      username: ${SPRING_DATASOURCE_DOMAIN_USERNAME}
      password: ${SPRING_DATASOURCE_DOMAIN_PASSWORD}
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect