# sweetspot-api/src/main/resources/application-server.yml

spring:
  datasources:
    auth:
      driver-class-name: org.mariadb.jdbc.Driver
      # 서버 환경에서는 DB에 직접 연결합니다. (예: localhost 또는 DB 컨테이너 이름)
      url: jdbc:mariadb://localhost:3306/sweetspot_auth
      username: ${SPRING_DATASOURCE_AUTH_USERNAME} # .env 파일의 변수를 그대로 사용
      password: ${SPRING_DATASOURCE_AUTH_PASSWORD} # .env 파일의 변수를 그대로 사용
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MariaDBDialect
            hbm2ddl:
              auto: validate # 서버에서는 스키마를 자동으로 변경하지 않고 검증만 하도록 설정
    domain:
      driver-class-name: org.postgresql.Driver
      # 서버 환경에서는 DB에 직접 연결합니다. (예: localhost 또는 DB 컨테이너 이름)
      url: jdbc:postgresql://localhost:5432/sweetspot_domain
      username: ${SPRING_DATASOURCE_DOMAIN_USERNAME} # .env 파일의 변수를 그대로 사용
      password: ${SPRING_DATASOURCE_DOMAIN_PASSWORD} # .env 파일의 변수를 그대로 사용
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            hbm2ddl:
              auto: validate # 서버에서는 스키마를 자동으로 변경하지 않고 검증만 하도록 설정
